# Generated by Django 5.1.3 on 2025-01-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='usage',
        ),
        migrations.AddField(
            model_name='grammar',
            name='romaji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='grammar_point',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='jlpt_level',
            field=models.CharField(max_length=10),
        ),
    ]
