# Generated by Django 5.1.3 on 2025-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, unique=True)),
                ('onyomi', models.CharField(max_length=100)),
                ('kunyomi', models.CharField(max_length=100)),
                ('jlpt_level', models.IntegerField()),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('meaning', models.TextField()),
                ('common_words', models.TextField(help_text='Comma-separated list of words')),
            ],
        ),
    ]
