# Generated by Django 5.1.3 on 2025-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_app', '0002_alter_kanji_common_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='stroke_order_svg',
            field=models.CharField(blank=True, help_text='Path to stroke order SVG', max_length=255, null=True),
        ),
    ]
